# =====================================================
# CONFIGURACIÓN DE LA APLICACION
# =====================================================

spring.application.name=tiendamotos

server.port=8080

# =====================================================
# ORACLE DATABASE 19c
# =====================================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=system
spring.datasource.password=Tapiero123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# =====================================================
# JPA / HIBERNATE
# =====================================================
pring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================================================
# THYMELEAF
# ==================================================
spring.thymeleaf.cache=false
